// LAYOUT MODULE & COMPONENT
export * from './lib/layouts/layouts.module';
export * from './lib/layouts/layouts.component';
// PUBLIC PAGES MODULES
export * from './lib/modules/public/public.module';
export * from './lib/modules/public/homepage/homepage.module'
export * from './lib/modules/public/blogpage/blogpage.module'
export * from './lib/modules/public/devspage/devspage.module'
export * from './lib/modules/public/docspage/docspage.module'
export * from './lib/modules/public/forumpage/forumpage.module'
export * from './lib/modules/public/legalpage/legalpage.module'
export * from './lib/modules/public/livepage/livepage.module'
export * from './lib/modules/public/marketpage/marketpage.module'
export * from './lib/modules/public/socialpage/socialpage.module'
export * from './lib/modules/public/storepage/storepage.module'
// PRIVATE PAGES MODULES
export * from './lib/modules/private/private.module';
// AUTH ASSETS MODULES
export * from './lib/security/assets/login/login.module';
export * from './lib/security/assets/register/register.module';
export * from './lib/security/assets/forgot/forgot.module';
export * from './lib/security/assets/reset/reset.module';
export * from './lib/security/assets/verify/verify.module';
